// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maquis_EvaluacionProgreso1_PrograIV.Migrations
{
    [DbContext(typeof(Maquis_DataBase_EvaluacionProgreso1_PrograIV))]
    [Migration("20250501134023_Esta es la primera migracion de datos")]
    partial class Estaeslaprimeramigraciondedatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maquis_EvaluacionProgreso1_PrograIV.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropietarioMascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioMascotaId");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("Maquis_EvaluacionProgreso1_PrograIV.Models.PropietarioMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Deuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TieneDeuda")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PropietarioMascota");
                });

            modelBuilder.Entity("Maquis_EvaluacionProgreso1_PrograIV.Models.VisitaVeterinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoMedicacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<int>("MotivoVisita")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereMedicacion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.ToTable("VisitaVeterinaria");
                });

            modelBuilder.Entity("Maquis_EvaluacionProgreso1_PrograIV.Models.Mascota", b =>
                {
                    b.HasOne("Maquis_EvaluacionProgreso1_PrograIV.Models.PropietarioMascota", "PropietarioMascota")
                        .WithMany()
                        .HasForeignKey("PropietarioMascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropietarioMascota");
                });

            modelBuilder.Entity("Maquis_EvaluacionProgreso1_PrograIV.Models.VisitaVeterinaria", b =>
                {
                    b.HasOne("Maquis_EvaluacionProgreso1_PrograIV.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
